label tunnel:
    ## The Tunnel Entrance
    ## EXT. Entrance to Utility Tunnel
    s "So I’m guessing this is the spot?"
    b "Pretty much."
    "After a short bus trip to the edge of the city, we finally arrived at our destination:"
    "One of the city's old utility tunnels."
    "Back before I was even born, this place used to have an entire network of tunnels to carry water and electricity for the entire city."
    "But after magic was introduced, these old technological marvels became a waste of space, and eventually forgotten."
    "Though, while these tunnels have no use anymore, they’ve become a popular spot for urban explorers due to the creepy atmosphere and winding pathways."
    "Basically, it’s a modern labyrinth."
    "Also known as, clout chaser bait."
    "And if the intel we got is true… It also has its own monster."
    s "Alright, first order of business: We set up a base camp here by the entrance, and then discuss a line of surveillance shifts."
    s "One of us should scout ahead and place these portable surveillance cameras in points and-"
    s "Wait, where are you going?"
    "I look up and see Breeze walking into the tunnel without thinking."
    s "We’re supposed to think of a plan before we go in!"
    s "This is a recon mission, remember?"
    s "If we do that, we’re just gonna get caught!"
    b "What seems more suspicious? Two idiots wandering aimlessly in whatbseems to be a typical case of urban exploration…"
    b "Or two people camping out in front of a service tunnel in the most obvious stakeout in history?"
    s "That’s…"
    s "I had to admit, he got me there."
    b "Action speaks louder than words, so I say we go in, find the vibrant, kick its ass, and go home!"
    s "But what if it’s connected to some evil group like the administration or-"
    b "Somehow, I doubt that."
    b "If there was really a group behind this, there wouldn’t even be evidence surrounding them in the first place."
    b "More than likely, this Vibrant is just a new breed that’s trying to hide out and ended up mutating further due to being underground for so long."
    s "Well…"
    "I look at him, clearly unsure if I should follow the veteran’s advice."
    "But if this is how they do it in the field, who am I to complain?"
    s "Alright, but what happens if someone catches us down there anyway?"
    s "What’s your plan?"
    "There were many answers to that question."
    "But the answer I got was not what I expected."
    b "YO, IT’S YA BOI B-FRESH HERE, COMIN’ AT YA TO INVESTIGATE THIS SPOOKY TUNNEL FROM HELL! STAY TUNED FOR THE PROMO CODE FOR 15% OFF YOUR NEXT PURCHASE OF-"
    "I slap him just out of pure instinct. Like every single cell in my body, every one of my long-gone ancestors, every version of me across the multiverse… in unison, just wanted… whatever THAT was to stop immediately."
    s "What… the actual hell was that?"
    "I say that not out of anger."
    "But pure… genuine… fear and revulsion."
    "Breeze, who took that slap like a champ, returned back to normal as if that break in character never happened."
    b "That was my influencer persona."
    b "If we ever do get caught I’ll just play my role as B-Fresh with you as my camera girl."
    b "It’s worked out for me in the past when I do get caught."
    b "The police are actually well acquainted with me and my channel, and I’m seen as more of an annoyance than an actual threat."
    "I take a moment to process exactly what he just said to me."
    "Then, like a worm burrowing into my brain, I suddenly remembered something."
    s "Wait, I know you!"
    s "You’re that idiot who posts those annoying videos that fill up my Tootoob Feed!"
    b "Grk-!?"
    b "You… You’ve seen them?"
    s "Uh, yeah."
    s "Kinda hard not to when your recommended videos get loaded with cringy influencer vids after you watch one!"
    s "Seriously, how does a guy like you get so many views with that terrifying performance!?"
    s "Not to mention your Vtuber model is way Hotter than the actual deal!"
    b "It’s just a cover identity.."
    b "All I do is send the videos to the people in our group who know how to edit stuff. They do the rest."
    b "Personally, I don’t care what they have B-Fresh say as long as it gets the job done."
    b "... but what does it matter if it makes me wanna kick my own ass…"
    s "What was that last part?"
    b "Nothing."
    "Let’s just go in."
    s "Wait, are we seriously just gonna barge in? Just like that?"
    b "Yeah, what about it?"
    s "Well I’m just not mentally prepared for this so-"
    b "Remember what I said back in the cafe?"
    s "... What?"
    "My mind blanked out for a moment as I tried to remember what he was talking about before he suddenly sighed."
    b "I said, to be more flexible in how you approach your problems."
    b "Everything you learn by the book and in a training ground can only go so far when you’re about to fight a Vibrant."
    b "So Be Sharp, Be Adaptive, and Be Creative on how you approach circumstances."
    b "Do that, and you’ll go far in this line of work. Or, at least, you likely won’t die horribly."
    s "Really trying to follow that, but I feel like we’ll just be put in danger if we just barge in."
    s "What if we’re in over our heads, and we’re in a situation we can’t escape from."
    b "Well, then let me tell you the one rule I actually listen to in our little club."
    b "No matter what happens, everyone must come back alive no matter what."
    b "As long as everyone is able to come back home alive, then that’s a victory."
    "And like that, Breeze continued to walk into the tunnel, once again leaving me behind."
    "While I was starting to notice a pattern here, I decided to shrug it off to follow him."

    ## Inside the Tunnel
    ## EXT. Tunnel Interior
    "Me and Breeze stuck close, and wandered the indistinguishable halls of this urban labyrinth."
    "During the whole trip, we were silent, with nothing but the faint dripping of water and the sound of our footsteps echoing across the vacant tunnel."
    "The silence helped me sort out my thoughts about the whole situation."
    "From meeting Breeze and the Boss, to searching for an actual Vibrant hidden by a possible government conspiracy."
    "It let me take in, that I’m currently knee-deep in an operation, ready to overthrow the established order."
    "It also made me think twice about what I was doing when I also realized that I’m in a dark creepy tunnel with an actual monster beyond my comprehension… also a new-type of Vibrant might be nearby."
    "The reality of the situation hit me hard on that revelation."
    "The creepy atmosphere didn’t bother to calm my nerves either, and the further we went in the more anxiety I felt crawling down my spine."
    "Of course, I wished someone would be a little more talkative to help lighten the mood. Maybe it wasn’t ideal, the manual also recommends strict radio silence, but this place is so creepy and gross that if I don’t have something to keep my mind occupied, I might just bolt at the first sign of danger!"
    ". . . . .  ."
    "But I couldn’t think up any good topics, and he didn’t seem to be in the mood for talking. It was honestly more awkward to try to force conversation than to just walk in silence."
    "And so we continued to walk for what seemed to be like hours until we finally arrived."

    ## EXT. Tunnel Interior (Graffiti?)
    "We entered a chamber that was slightly more spacious than the neverending tunnels we were walking through."
    "From our Intel, this was the exact location that poor streamer was attacked by that Vibrant."
    "While the attack happened a while ago, there were still some clean signs that something happened here."
    "One: A lone broken phone shattered across the ground."
    "And Two: An uncompleted Graffiti Tag the Streamer and his buddy were working on."
    "The work was pretty good despite the fact that it was half-finished."
    "But the biggest standout of the work was something that shouldn’t have been there."
    "A mysterious dark red streak that was vicariously splattered across the concrete canvas."
    "While it looked like paint at first, upon further inspection, it could have only been one substance…"
    "Blood."
    b "Alright, I’ll go search that side, you go to that side to see if there’s anything there."
    "I merely nod my head as I scour the room for any clues to the Vibrant’s whereabouts."
    "As Vibrants are monsters that ooze magic corruption out of their pores, they always leave a faint trace of magic behind, wherever they go."
    "And if this vibrant is as strong as intel implies that means-"
    b "Found it."
    "I turned my head only to look in shock as Breeze was licking a strange red crystal in his mouth."
    "I immediately knock the crystal out of his hand as I stare at him like a mom who caught her kid touching something he shouldn’t."
    s "Could you please tell me why you had the sudden urge to lick the Vibrant equivalent of feces please?"
    s "We have tech and magic… Why would you lick something off a filthy sewage stained floor!?"
    b "... It’s the best way to know how potent magic corruption is."
    b "It’s sweet but teetering on the edge of being sour, so the corruption is quite severe and oh god you’re right, what the hell am I doing?"
    s "Are you some kind of dog?"
    s "There are some easier ways to track down Vibrant magic, you know?"
    "After lecturing my superior, I went over to the crystal fragment, and picked it up."
    "I grimaced as I wiped away Breeze’s saliva before I pulled out my phone."
    "And then, aiming the camera at the crystal in my hand, I utilized a custom app to scan the sample."
    "Once the analysis was complete, I began to do the same thing to the entire room, and began to scan for any traces of the vibrant."
    b "Looks like the Boss supplied you with some new piece of tech."
    b "Neat."
    s "Actually this equipment has become standard for a while."
    s "I’m surprised you don’t have it since you’ve been a field agent for a while."
    s "... Wait a minute."
    s "How long have you been in this organization for exactly?"
    b "A while."
    s "... Was there any reason you joined."
    b "Same reason anybody else joins."
    s "..."
    s "You’re really not good at banter, are you?"
    b "...Nope, I’m usually a solo act. People tend to find me a bit…."
    s "Abrasive? Unusual? Mean? Jerkish?"
    b "I was gonna say \"hard to work with\" but yeah, all that stuff probably applies too."
    s "Well, it certainly explains your lack of social skills."
    s "But weirdly enough, I’m glad."
    b "Why is that?"
    s "I thought I would be the awkward one on this mission."
    s "It’s kinda soothing, knowing your partner is also a bit of a weirdo like me."
    b "..."
    b "... you’re welcome?"
    s "What was that?"
    b "Nothing."
    s "... If you say so."
    "..."
    b "..."
    s "Hey Breeze, you said you don’t usually work with a partner, but that didn’t mean you worked with someone in the past."
    "What were they like?"
    b "..."
    b "... Well they were-"
    ## BEEP BEEP BEEP
    "At the sound of that alarm, I looked back at my phone and saw that it finally traced the vibrant’s magic signal."
    "But before I could say anything, Breeze took my phone and immediately skimmed through the intel."
    "Upon finding what he was looking for, he quickly handed me back my phone before walking off in the direction of the signal."
    "And, once again, I ran after him."
    s "You know you could just wait for me, right!?"



    ## Following the Signal
    ## EXT. Tunnel Interior
    "And so, once again, we traveled the ever-expanding labyrinth to search for our target."
    "The journey felt a lot easier this time though since the closer we got to the signal, the stronger the magic residue became. "
    "We soon reached our destination and what we saw there was… gruesome to say the least."

    ## EXT. Bloodstained? Room
    "There was no real way to describe the exact details of the area around us."
    "But it looked like a Tornado suddenly appeared in this room, and started juggling chainsaws in an effort to kill whatever was in here."
    "While the red stains that were everywhere were too bright to be blood, it didn't stop me from becoming nauseous of the possible carnage that unfolded here."
    b "Looks like someone beat us to the punch."
    "Breeze suddenly walked up and began to survey the area."
    b "The fight wasn't clean though."
    b "If it was, there wouldn’t be so much damage all over the place."
    s "Obviously."
    s "What exactly does that mean though?"
    s "Was it trying to defend its nest in some way?"
    s "If its hunting ground is around this area then it would probably be vigilant if someone was closing in on its home."
    b "No. Not likely. "
    s "What do you mean?"
    b "If it was trying to protect its territory we would've noticed any territorial marks around the tunnels somewhere like claw marks on the pipes or leftover bones from a meal."
    b "But other than the magic corruption, there was nothing to imply that this creature actually had a nest yet"
    b "This isn't adding up with our intel…"
    s "Maybe it was attacked or something?"
    s "We're not the only ones who are capable of dealing with Vibrants after all."
    b "... We're not the only ones who deal with Vibrants…"
    b "..."
    b "..."
    b "That's it!"
    b "Hey Newbie! Do you have anything on your phone that can scan for non-magic related things?"
    "I look at him for a moment confused, until I realize what exactly he's planning."
    "Without missing a beat, I pull out my phone and activate another app before scanning the floor."
    "And, just as we expected, we saw clear traces of multiple fresh footprints too numerous to just be our own."
    "Dozens of these tracks going in and out of the area."
    "And since these tracks looked fresh, that meant only one thing."
    "Someone was patrolling the area."
    " *Thump Thump Thump* "
    "As if on cue, we heard the sound of footsteps and the vague sound of voices heading towards our direction."
    "But before I could react, Breeze suddenly grabbed me by the waist."
    s "Hey what are you- mmph!?"
    "And then he used his free hand to cover my mouth."
    "Then, without so much as a warning, a veil of cold air surrounded us. Perfectly cloaking us in an invisible field of magic."
    "While I was still mentally recovering from the sudden adrenaline rush, I immediately understood what he was trying to say as I kept my mouth shut."
    "And, at that moment, they appeared."
    g1 "Remember when commercials used to be fun and creative without pandering to the demands of nitpicks?"
    g2 "Yeah, we need more stupidly fun stuff because that’s what makes that shit memorable."
    g1 "Like watching a Water Bottle get cucked by Fruit."
    g2 "Or watching a Panda break your TV because you didn’t eat your cheese."
    g1 "Oh god *chuckles*"
    g2 "Ok ok, but seriously, we should probably check for intruders."
    g1 "You think it was another streamer or something?"
    g1 "You’d think that nearly getting devoured by a Vibrant would teach them, but some people just seem to have a death wish."
    g2 "Well whoever it is, is in big trouble."
    g2 "Security had to grow tighter after that initial breakout, and now we’re stuck working overtime because of that last idiot."
    g2 "It better be a rat, trippin’ the sensors otherwise they’re gonna be sorry…"
    "I look at the late arrivals as they slowly scour the area for our presence."
    "Luckily, Breeze had the brilliant idea of hiding us in mist, so we were probably well hidden."
    "But the safety of my tubular canopy allowed me to think clearly about certain matters."
    "Like the fact that someone else really is down here."
    "And from the sound of it, they’ve been here for a while."
    "This certainly confirms that something strange is going on here, so the proper order of business is to get out of here, and report to HQ-"
    s "Hey, guys! How’s it going?"
    s "... I should’ve seen this coming."
    "Before I could question if Breeze had any proper training, he grabbed me once again as he dropped back down to the floor."
    "We landed with a loud thud as the two goons turned to see us."
    "But the shocked expressions they had immediately twisted into faces of exasperation and groaned at the sight of us."
    g1 "Oh no. Not you. Why did it have to be you!?"
    g2 "I swear, it’s almost like you know when we’re on guard duty so you can jump us."
    g2 "EVERY! SINGLE! TIME!"
    s "... Friends of yours?"
    b "More like acquaintances. I call them Goon 1, and Goon 2."
    g2 "I never agreed to that name you know!"
    g1 "Yeah, as much as I like being \"Number 1\". It demeans us as people if you just treat us like mobs in a game!"
    b "Yeah yeah yeah, let’s just cut to the chase."
    "Breeze suddenly began to pull out his sword."
    b "What’s the MRF doing here?"
    b "And what is your relation to this new vibrant?"
    "My ears perked up when I heard the notorious acronym of MRF."
    "Better known as the Magic Restoration Front, the MRF is a group of Pro-Magic Zealots who answer to the beck and call of the Administration."
    "Simply put, they’re not only the lapdogs of the entire government, but an organization composed of some of the most powerful mages in the entire country."
    "And to make matters worse, they’re our group's arch-enemy."
    b "Come on, at least make a comment or something."
    b "This is basically routine for us."
    b "So, you can save yourself some pain by giving me the information. Or I’m going to literally beat one of you into this disgusting sewer floor, using the other as a hammer."
    "The goons looked at eachother, and then back at us."
    "Silently, they whip out a couple of weapons on their hips and brandish them at us."
    "The Grim expressions on their faces told us everything we needed to know about what they think about Breeze’s proposal."
    b "... Well I guess it's the hard way then."

    # [Fight scene here]
    g1 "You know you could've held your punches right!? Why'd you hit us harder than usual!?"
    g2 "Yeah man, I still have bruises from last time!"
    b "I did give you a choice and you picked the stupid option. Also, I wanted to show off to the newbie here. It's her first day after all. Likely won’t be the first first time she kicks your ass either."
    "Everyone turned their heads toward me, causing me to blush a little at their attention."
    s "... Shouldn't we get to the interrogation part of this now or?..."
    b "Oh, right."
    "We looked back at our newly defeated guests."
    "Seeing as they have ties with the MRF, they should have information in regards to this new vibrant area hanging around here."
    "Of course getting the information is just the second part of the battle."
    "And seeing as how we kicked the switch out of them, it's going to be harder for them to talk."
    "So the question is… who should interrogate them?"

    menu:
        "Who interrogates the goons?"
        "Sofi":
            s "Alright, time to put those interrogation sessions to work…"
            "I immediately put up my angry face, and I approached the men ready to get the information out of them."
            s "Alright Goon 1, tell me what exactly the MRF is doing here or we'll get the information one way or another!"
            g2 "I'm Goon 2"
            s "... oh."
            g1 "Look Missy you seem clearly new, so I'm just going to give it to ya straight."
            g1 "Quit now before it's too late."
            g1 "I don't know what kind of shit the Administration did to get on your bad side but you're just another sob story out of the hundreds already told."
            g2 "If Breeze wasn't here to cover your ass, I bet you would've blown your cover on the first day!"
            s "T-That’s not!"
            g1 "See you're already fumbling on your words!"
            g1 "You expect us to take you seriously?"
            g2 "What a joke!"
            "The two goons laughed their asses off despite the fact they were in pain."
            "As for me, I simply dropped my shoulders as I realized that interrogation was a lot harder than it looked."
            "But just as I was about to call them out, I felt a light tap on my shoulder."
            "Turning around, I see Breeze with a stern expression on his face."
            "He looked mad."
            b "Watch closely newbie, This is how you interrogate someone."
            "Breeze then calmly walked to the laughing goons and pulled out his sword."
        "Breeze":
            b "Alright, let's get this over with."
            "Breeze calmly pulled out his sword and proceeded to walk towards the goons menacingly."
            "The goons flinched, but immediately tried to mask their fear."
            g1 "H-Hey! Hold on a second! Let's talk about this!"
            g1 "We've known each other a long time! So we're used to your interrogation tactics!"
            g1 "S-so by that logic, there's nothing you can do that will make us talk anymore!"
            g2 "Y-Yeah! What he said!"
            "Just as Breeze was about to bring his sword down, he stopped."
            "And for a moment, he thought about what he said."
            b "Huh… I guess you're right."
            g2 "He is?"
            g1 " I am?"
            g1 "I mean… of course, I am!"
            g1 "So don't think we're going to talk just because you beat us up!"
            "For a moment Breeze was in deep thought when he suddenly had an epiphany. "
            b "Well I guess I won't beat you up for info."
            b "I'll let the newbie handle that!"
            s "Say what?"
            g1 "Are you serious? You're gonna let this greenhorn take over?"
            g1 "Whatever could she possibly do?"
            g2 "I bet she couldn't even harm a fly with those noodly arms!"
            g1 "I bet she can't even kick anyone's behind with those flabby thighs!"
            g1 "It's like all the meat that was supposed to be on your body moved down to your thighs! You fat bitch!"
            g2 "Good one, mate!"
            "The two goons shared a laugh at mocking me."
            "But that was quickly shut down when I slammed the wall with my bare fist."
            "The impact left a decent crater, leaving a good impression on how strong my "Noodly Arms" really were."
            s "Hey Breeze, can you give me a minute?"
            s "I have an idea on how to get these guys to talk."
            b "Heh, by all means go ahead."
            "Breeze then walked out the room, leaving me with the quivering goons who had the bold idea to insult a lady's body figure."
            "Walking up to them, stretching my body out a little for the \"warm-up\" I was going to have."
            "Now then… let's have a chat, shall we?"

    "What happened next was a little too violent to describe but by the end of it, the Goons were talking."

    g1 "Ok! Ok! We surrender, just please stop hitting us!"
    g2 "Ask whatever you want! Just don't hurt us anymore!"
    s "I think they're ready to talk."
    b "Seems like it."
    "And so, the Goons began to spill everything they knew about the MRF's operation."
    g1 "This operation has been going on for weeks, we've been transporting vibrants through these tunnels to a facility deep underground."
    g1 "I don't know what they're researching, just that it involves a lot of Vibrants."
    g2 "One got out last time and now the head honchos are paranoid and thinking of pulling the plug on the whole operation."
    g2 "They've been moving equipment and resources out of the base for a few days now. It’s basically a skeleton crew down there."
    g1 "That’s all we know! We're just low-level grunts!"
    g2 "They don't tell us anything because of this situation!"
    b "Is that everything?"
    g2 "I forgot to shave my armpits last week!"
    s "TMI, Goon 2. TMI."
    b "See? You're getting it."
    "Breeze suddenly patted my back"
    "Though it was hard to see in the dark dank tunnels, I could've sworn that he was smiling."
    g1 "So now that we told you everything, will you let us go?"
    b "I never recall agreeing to that…"
    "Breeze glared menacingly at the goons causing them to flinch."
    b "And who said you told me everything?"
    b "We got one more question left before we're done with you. So you better spit out the answer quickly before we gotta beat it out of you again."
    "The goons can only nod frantically as they answer Breeze’s last question."
    "Of course, Breeze still wanted one last favor before we left…"

    ## Inside the Facility:
    ## EXT. Magic Facility

    ms "About time you guys got here!"
    ms "Your patrol was supposed to end 2 minutes ago! Now hurry up and start moving boxes!"
    s "Roger that sir! We’ll get right on it!"
    b "Don’t expect us to hurry though, I go at my own pace."
    ms "Yeah Yeah, whatever. Just get to work."
    ms "..."
    ms "There’s something different about you bozos today…"
    s "..."
    b "..."
    ms "...Did you get a haircut?"
    b "Finally shaved my armpits!"
    ms "Gross… Just get to work!"
    s "..."
    s "Really, you shaved your armpits?"
    b "Goon 2 admitted it himself. Have to keep our stories straight."
    b "Otherwise we would look suspicious if we don’t act like them a little."
    "Earlier before we came here, we got the exact location of their base from Goons 1 & 2."
    "After using a handy gadget that allows us to disguise ourselves as the Goons, I used my app to detect for any energy sources to make sure they aren’t lying."
    "And as I was searching, I discovered that the MRF was using the old utility lines to power this facility to hide their presence."
    "It was a clever tactic seeing as we would never be able to detect their activities with magic sensors."
    "Old-world tech was basically invisible to people nowadays."
    "Still, since this was old-world tech, the power output was drastically lower compared to an actual magical power plant."
    "So the tech we saw was barely even running by itself."
    "The Magic Scientists were practically working overtime just to keep their machines alive."
    "Unfortunately we could only take small peeks as we didn’t want to alert the facility that we’re not the people who we say we are."
    "That didn’t stop me from secretly taking photos with my phone though."
    "It was easier to be discreet when these researchers were more focused on maintaining their priceless machines in a hazardous environment."
    "By the time we walked into a decently clear area, I had already gathered enough evidence of their activities to spark a revolution 10 times over."
    "And as an added bonus of a recorded confession from Goons 1 & 2, there was only one thing left to do…"
    s "Protocol dictates that we should fall back immediately to a safe location."
    s "Then we have to send this data back into HQ, and wait for further instructions."
    b "Alright. Sounds good to me."
    "The moment I heard those words, I knew something was off because…"
    s "This is the first time you actually agreed to a written protocol…"
    s "... You’re going to add a \"but\" to that statement, aren’t you?"
    b "No…"
    b "..."
    b "Buuuutt…"
    s "There it is."
    b "This is a serious suggestion, though. Remember what Goon 2 said earlier?"
    s "That they were moving their stuff, right?"
    b "Exactly, which means that they won't be around here any longer."
    b "By the time reinforcements arrive, they will probably realize they've been compromised and destroy this place to wipe their tracks."
    s "That’s… a good point actually. "
    b "So I say we take care of this now, rather than later!"
    s "But this is supposed to be a reconnaissance mission! The boss told us not to be reckless, remember?"
    b "That's what she says in all my missions. I still do things my way regardless, and she hasn't kicked me out yet."
    b "So are you in or out? It's your call newbie."
    s "... Fine, but if this goes south I blame you!"
    b "Fine by me!"
    s "But first we need to come up with an actual strategy. "
    s "These disguises aren't perfect and if someone here is smart enough to see through our shoddy facades, we're dead!"
    b "We just sneak around. Shouldn't be too hard, especially with my skills."
    s "This place is probably equipped with foreign magic sensors, so they'll spot us right away."
    s "And with so many people still running around here, I say it's next to impossible to sneak around."
    s "Maybe if we had a distraction of some kind, it would be a different story but I don’t see how-"
    "BOOM!!!"
    "Out of nowhere, an explosion seemingly went off as the alarms in the facility started blaring."
    fi "ALERT. SECURITY BREACH IN SECTOR 3."
    fi "REPEAT. SECURITY BREACH IN SECTOR 3."
    fi "NON-COMBATANTS ARE TO EVACUATE TO THE NEAREST EXIT AS SOON AS POSSIBLE."
    fi "ALL COMBATANTS ARE TO CONTAIN BREACH IMMEDIATELY"
    "We immediately went on guard as soon as we heard that message."
    "Did they find us out? I wasn’t sure until I saw a couple of guards literally run past us."
    b "Might be another Vibrant breakout."
    b "Talk about a lucky break."
    s "Weird coincidence, but this is definitely a golden opportunity."
    s "Let’s move!"
    "Seizing this fortunate chance, we immediately began to bolt to the opposite direction the guards were going to shut down their operation."
    "But the thing about luck is that it’s a fickle mistress because just as we thought we were home-free, we get flagged down by someone I could only describe as… beefy."
    u "Hey, you! Where are you two going!?"
    "Seeing as we were caught red-handed, I quickly tried to come up with an excuse to tell him."
    s "Sorry sir, we just got back from our patrol! We were just going to take a quick trip to the bathroom before getting back to work!!"
    u "Hold it in then! We got an emergency breach, and we need all hands on deck!"
    "Just then the big guy’s communicator went off, to which he reluctantly answered."
    u "Yes, Dr. Tomo?"
    "..."
    u "Can’t you just wait in the safe room like you’re supposed to? The break-in just released a majority of our Vibrant subjects and if anything were to happen to you, this operation is compromised."
    "Worse comes to worst, we’ll have to initiate Operation Exodus."
    "..."
    u "Can’t this wait until after I deal with the Vibrant outbreak!?"
    "As the Beefy man continued to speak, I couldn’t help but look at Breeze."
    "For a moment I thought my excuse for us to go to the bathroom was legit but, upon closer inspection, Breeze was glaring at that guy."
    "But it wasn’t just his eyes, Breeze’s body language and the way he was grinding his teeth under his scarf told me that these two probably have some history."
    "And not the good kind."
    "It was almost frightening to see the level-headed weirdo get so worked up all of a sudden."
    "Luckily, the beep of the man’s transmitter broke me out of my trance as he looked back at us."
    "Alright, I need you guys to do something for me… Is he glaring at me?"
    s "He’s probably just annoyed that he didn’t get to take a quick bathroom break."
    b "Yeah… that."
    u "..."
    u "Whatever, doesn’t matter."
    "The man suddenly pointed at me."
    u "You, head over to Dr. Tomo’s safe room over by Sector 4."
    u "Just walk straight and take a left at the third hall."
    u "Your task is to guard her with your pathetic life! Understood!?"
    s "Y-Yes Sir!"
    "I responded reflexively to keep my cover, as he turned to Breeze."
    u "You, you’re with me on containment duty."
    b "Roger that… sir."
    "The man walked away to his destination. Just as Breeze was going to follow him I grabbed his and quickly whispered something in Breeze’s ear."
    s "I don’t know what your history is with this guy, but you need to calm down."
    s "Your malice is so potent, that even a rookie like me can feel it."
    "Breeze turned his head away, more annoyed at my advice than anything."
    "But I wasn’t going to just move to his tune this time, so I grabbed him by his scarf and looked him dead in his eyes."
    s "Listen, to me. I don’t know what just happened but we literally struck a gold mine to blow this whole operation over just like you wanted."
    s "So for once, follow the mission and don’t blow your cover… please?"
    "The senior field operative looked at me with a widened expression, before falling back to his normally stoic face."
    b "...Alright, I’ll try."
    s "Thank you."
    u "What are you slackers doing!?"
    "We both look up to see the big man glaring at us."
    "Seeing as we should probably move to our \"stations\" we nodded in silent agreement as we split up to perform our \"duties\"."

    return
