label chapter6:
    # Elevator ding sound
    play sound "audio/ding.mp3"
    tm "The Elevator is open! Hurry inside! Now!"
    play music flairtheme fadein 1.0
    "Upon hearing the signal, the three of us immediately retreated towards our destination."
    "With the remaining Vibrants in hot pursuit, we booked it as hard as our legs could carry us until we crossed the elevator’s threshold, the doors snapping shut just before the remaining vibrants could so much as cross one of their deformed snouts past the door."
    "Only once we felt the elevator moving, and the sound of the vibrants scratching at the door growing silent, did we finally breathe a unanimous sigh of relief."

    jump startend ## at script.rpy
    
    # All characters let out a sigh of relief
    # btw for character positioning… breze and sofi should be next to each other, while Alverna and flair are next to each other, so it should go something like: B S F T

    s "I would like to not do that again, thanks."
    f "Yeah, I have to agree with Sofi. On their own, vibrants at that stage are small fry. But then add a hundred of them all at once…"
    "Breeze merely nodded in silent agreement."
    "We all took a moment to catch our breath, before we moved on to the next order of business."
    tm "Ok, let me be the first to ask: You’re obviously not with the MRF, so who the hell are you people?"
    tm "Secondly, Flair… why are you here?"
    "The doctor turned to all of us for an answer and the first to respond was Flair."
    f "Obviously trying to look for you!"
    f "Mom’s been trying to contact you for nearly a year! You weren’t at your home, your colleague hadn’t seen you, it was like you just disappeared out of nowhere!"
    f "You’re lucky I was able to find you so soon. I would’ve burned this place to cinders just to look for ya!"
    tm "Still as violent and headstrong as ever, I see…"
    f "Don’t I know it!"
    f "...Wait a minute-"
    tm "Are these people also with you?"

    # beat, Flair and Breeze look at each other, then turn back to Alverna

    b "I have no idea who this psycho is."
    f "Same here."
    tm "Huh… so if Flair was the intruder that triggered the alarms, and she’s not with you, then once again… who are you people?"
    "The two girls looked at us, expecting an answer."
    b "We're with the-"
    s "We're with a Group of Freelancers interested in the reports of a Vibrant recently."
    "I quickly glance at my partner, with a stern glare."
    "I haven't known Breeze for a long time, but from my limited interactions with him so far, I had a good feeling that he was just going to blab about who we were."
    "Because as much as this guy likes to talk like a professional, he doesn't really do much to follow that example."
    tm "Just freelancers, eh?"
    tm ". . . . ."
    tm "Seem pretty well-trained to just be freelancers?"
    b "Let’s just say that I’m used to this sort of work."
    s "And I… have beginner’s luck?"

    # hold on Sofi for comedic timing

    tm "Riiiiiright… wait, you said a vibrant report. Are you talking about the one from a little while ago?"
    s "Yeah, that one, it was caught on camera, it was circulating around the web, so we were contracted by a reporting agency to check it out. Did you hear about it?"
    tm "...I was aware of it, but I thought they already covered it up?"
    f "What do you mean by that?"
    tm "Well, I overheard my guards talking about one of the research subjects breaking out of its containment cage and managed to get to the surface. But that’s about all I know, they weren’t exactly keen to tell me everything that goes on… "
    tm "Since I was busy you know… being kidnapped."
    f "See, I knew you were kidnapped! The moment I saw you with those shady guys, I knew you were caught under a trap."
    tm "I won’t deny that."
    tm "I was offered a cushy government job by one of my mentors in the scientific community. Apparently, someone was retiring and they floated my name as a replacement, I think they were trying to put together a report on Vibrant migratory patterns? Since my degree had to do with the study of magical creatures and vibrants… seemed like a natural fit."
    tm "But when I arrived at the location, they took me to a room, and they must’ve gassed the room or something, because I started to feel very sleepy. I thought it was because of the all-nighter I pulled preparing for the interview, but I fell unconscious and found myself here when I woke up."
    tm "I was then threatened to help develop some sort of bio-weapon for these people. I wasn’t exactly sure what, since I was mostly kept in the dark."
    b "Hmmm, the project’s name they had you working on, it was called…"
    s "Project Siren. Though, they didn’t know anything about it"
    tm "Yeah, that’s the one! All I know is that they’ve had me and the other scientists here doing some experiments on vibrants? I don’t know why they’d want to do that, but I wasn’t about to see where their tolerance for insubordination was. So… I kept quiet and just did what I was told while waiting for a chance to escape."
    b "...Is that it?"
    tm "Yep. That’s all I know, I swear!"
    "Flair immediately patted Alverna’s shoulder to comfort her friend."
    f "Well, you got nothing left to worry about, I got your back."
    "But as for me and Breeze, we looked at each other for a moment as if we were reading each other's minds."
    "There’s something she’s not telling us."
    "We didn’t have any solid proof, but something about what the Doctor said just didn’t add up."
    "But without evidence, we couldn’t explain anything to Flair without sounding paranoid."
    # turn breeze sprite to Sofi

    "Breeze then pointed to me, the doctor, and finally his eyes."
    "I nodded in response, knowing exactly what he just told me do."
    f "Hey, are you guys listening?"
    # turn breeze sprite back
    "We both turned to our temporary ally, as we stopped our silent conversation."
    s "Sorry, just in deep thought. What was it you were saying?"
    f "I was saying that we should ditch this place now.."
    f "I only came for Alverna, and you guys probably only came here to get info, right?"
    s "That’s… correct, right. Yeah. Why?"
    f "Then you probably have all the evidence you need now, right? I mean… look around you, what more evidence do you need?"
    b "She’s not wrong, you’d have to be an average senator to look at this whole operation and think it’s totally normal and on-the-level. You gathered evidence, right?"
    s "Oh yeah, tons of it. Sixth chapter in the manual has a section on gathering evidence."
    b "Good job."
    f "Also Alverna here can serve as a witness, right?"
    f "Whatever they’re doing here doesn’t matter to me. I got what I came here for, so I don’t see any reason to stay here."
    s "Hmmmm…"
    s "Personally, I don’t think we should leave things like this. However… we’re at a major disadvantage here. The manual says that an agent should avoid engaging with an enemy when they control the battlefield. So, we should fall back and report in."
    b "Alright."
    s "Okay I know you don’t like the manual, but this is obviously a time whe-- Wait what?"
    b "Was there something wrong with what I said?"
    s "Oh, i-it’s nothing. I was just surprised you actually agreed with me for once."
    b "Don’t get used to it rookie."
    b "Relying solely on the manual makes you a predictable agent. However, in this instance, the manual is correct."
    b "The right move here would be to fall back for now."
    s "Oh… Ok…"
    s "Right. Soooooo, I guess I’ll just try to plot us an exit out of here and-"
    tm "I disagree."
    "We all looked to Alverna, who had a serious expression on her face."
    f "What are you talking about Alverna?"
    f "You were kidnapped right?"
    f "Why wouldn’t you want to leave?"
    s "It’s that Vital thing you wanted to get right?"
    "Both Flair and Breeze looked at me in confusion at my sudden declaration."
    "I briefly explain to them that before they barged in, Alverna was already trying to unlock the elevator to retrieve something vital in another part of the facility."
    "Whatever it is, was beyond me though, since the Doctor didn’t want to explain."
    tm "All you need to know is that I can’t leave until I get it."
    b "That’s awfully suspicious of you."
    b "Is this item really worth risking your life over? Or are you asking to put all of our lives on the line for something you won’t explain?"
    tm "..."
    b "Look, we’ve just met and all, but you’re asking for something pretty big, and you’re not telling us why. So-"
    f "Hey, lay off!"
    "Flair stood between Breeze and Alverna, acting as a makeshift shield for the doctor."
    f "I admit, that this does sound suspicious, I get why you’d be hesitant, and yes maybe this is a mistake."
    f "But Alverna is my friend!"
    f "And we promised to always trust each other when we were kids. I always keep my promises, and I know Alverna wouldn’t ask this if it wasn’t important."
    ". . . . . "
    b "Are you prepared to die for a promise?"
    f "...I trust Alverna."
    "Breeze then got closer to Flair. Despite the small room, it looked like he was ready to physically drag the two out of them out of the facility when suddenly, the entire elevator started to rumble!"

    # shake the screen slightly, watch for the edges of the screen so the transparent bg underneath isn’t visible

    "We all tensed up, ready to spring into action if Vibrants started trying to peel open that elevator top."
    "....."
    "........................"
    "......................................................"
    "Nothing happened."
    "Or at least, that’s what we thought. Until the Intercom went off again."
    fl "ALERT! CONTAINMENT BREACH IN SECTOR 51!"
    fl "REPEAT. CONTAINMENT BREACH IN SECTOR 51! PRIORITY-0 SUBJECTS HAVE BEEN SPOTTED, EXERCISE EXTREME CAUTION!"
    b "This facility is literally falling apart."
    b "If the Vibrants aren’t contained soon, then the MRF will likely bury the evidence of this facility. Regardless of whether or not everyone makes it out."
    b "The longer we stay here, the higher the chances that this place will become our tomb."
    b "So, I’ll ask again. You can risk your life, but are you prepared to also risk ours for something you won’t even tell us about?"
    "We all stood quiet for a moment. Alverna in particular looked down sullen, as if in deep thought."
    "But just as Flair was going to reprimand Breeze, Alverna finally let our a sigh."
    tm "Okay fine, you’re right. If it was just me, then I’d just be risking my life."
    tm "But I don’t want to risk Flair’s life or yours, so… fine, we’ll escape."
    "My shoulders relaxed when those words came out of her mouth, relieved that this doctor might actually see reason."
    tm "However, considering the way we came is occupied by countless vibrants, we’re going to have to take another route to get out of here."
    f "Do you have any ideas, Alverna?"
    tm "This facility was designed with multiple escape routes in case of an accident."
    "The facility rumbled as if in response."
    tm "I’d say this counts as an accident."
    tm "Fortunately, I happen to know of an escape hatch down in the lower labs. So if we use that, we’ll be able to escape."
    tm "Since I can’t do what I came down here for anymore, we’ll just have to skip to the end. Usually, there’s guards there, but I figure that they… have probably already evacuated or if they are there…"
    tm "...I think you guys can probably convince them to stand down."
    tm "Truthfully, I was planning to go that route anyways if I ever found a chance to break away from my captors."
    "Flair then hugged the doctor, complementing her on the clever plan."
    "But as for me and Breeze, we could only look in worry as a bad feeling crawled up our spines."
    "Something didn’t feel right about her explanation. I couldn’t put my finger on it though."
    jump chapter7
    return
